<?php

$wp_tests_dir = getenv('WP_TESTS_DIR');

// Gives access to the function tests_add_filter
require_once $wp_tests_dir . '/includes/functions.php';

$basename = basename(dirname(__DIR__));

$GLOBALS['wp_tests_options'] = array(
	'stylesheet' => $basename,
	'template' => $basename
);

tests_add_filter('set_current_user', function($arg) {
	$user = wp_get_current_user();
	$user->set_role('administrator');
	return $arg;
}, 1, 10);

tests_add_filter('filesystem_method', function($arg) {
	return 'direct';
}, 1, 10);

/**
 * Registers theme
 *
 * Copied from the file generated by `wp scaffold theme-tests`
 *
 * @link https://developer.wordpress.org/cli/commands/scaffold/theme-tests/
 */
function _register_theme() {
	$theme_dir = dirname( __DIR__ );
	$current_theme = basename( $theme_dir );
	$theme_root = dirname( $theme_dir );

	add_filter( 'theme_root', function() use ( $theme_root ) {
		return $theme_root;
	} );

	register_theme_directory( $theme_root );

	add_filter( 'pre_option_template', function() use ( $current_theme ) {
		return $current_theme;
	});
	add_filter( 'pre_option_stylesheet', function() use ( $current_theme ) {
		return $current_theme;
	});
}
tests_add_filter( 'muplugins_loaded', '_register_theme' );

require dirname(__FILE__) . '/mock/mock-options-framework.php';
require dirname(__FILE__) . '/mock/mock-admin-functions.php';
require $wp_tests_dir . '/includes/bootstrap.php';
